name: base-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - octave_kernel
  - pyjanitor
  - boto
  - django
  - requests
  - nodejs=9
  - jupyterlab>=0.33
  - geopandas
  - simplejson
  - go 
  - rise
  - pip:
    - bash_kernel
    - jupyterlab_latex
    - prettyprint
    - mplleaflet
